### ISSUE TITLE
Are there any restrictions on the global ids assigned to graph vertices and edges?

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/EnGPar#10]
Do they have to be contiguous?  Is zero a valid id? Is any integer valid?

**Comment by diamog** [comment]
Just tested some of the various potential restrictions. The N-Graph can support arbitrary ids, noncontiguous and zero is valid but not required. An example serial graph can be seen here https://github.com/SCOREC/EnGPar/blob/master/test/buildGraphs.cpp#L262-L294
