### ISSUE TITLE
add split function to FORTRAN interface

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/EnGPar#13]
wrap or implement a splitter using the Zoltan API as shown below
https://github.com/SCOREC/EnGPar/blob/3c78cbc3439a726fb172ab46f2547443be002e01/test/pagerank.cpp#L193-L209

**Comment by diamog** [comment]
I wouldn't take anything in this file at face value. If I remember correctly this test program never quite worked correctly. Also after all this time, it probably doesn't compile...

**Comment by cwsmith** [comment]
https://github.com/SCOREC/EnGPar/commit/0fb7b72376a0becdad6668b85fd9a357d3b2e97e
