### ISSUE TITLE
add valgrind run of tests to nightly runs

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/EnGPar#17]
Assuming this is on a scorec system then we need:

```
module load valgrind
```

and a few additional CMake settings:

```
...
-DVALGRIND=valgind \
-DVALGRIND_ARGS='--log-file=vg.%p; --error-exitcode=1; --suppressions=/path/to/mpich3.supp' \
...
```

We'll also need to setup suppressions for MPI and any other system noise.

**Comment by cwsmith** [comment]
An valgrind supressions file for pachisi is attached
[mpich3.supp.gz](https://github.com/SCOREC/EnGPar/files/1598729/mpich3.supp.gz)
and in the repo 48adf0eb83b0a9314a4915289e97ee348e494f4f

**Comment by diamog** [comment]
The current implementation of this will report a failure when there is a memory error. The tests do pass if there is a memory leak

**Comment by cwsmith** [comment]
Hmmm.  They should fail with the `--error-exitcode=1` argument.  In `Testing/Temporary/LastTest.log` we should be able to see these args passed on the command line.

**Comment by diamog** [comment]
Yeah I think you are right. It seems to only be taking the first argument of the VALGRIND_ARGS when doing the nightly test.

**Comment by diamog** [comment]
the arguments are now correctly being passed to CTest
