### ISSUE TITLE
build breaks when parmetis is disabled

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/EnGPar#18]
It looks like engpar_split.cc relies on parmetis.

**Comment by diamog** [comment]
What exactly fails? If parmetis is not turned on and you try to call the split routine using parmetis it will throw an error stating that parmetis is not enabled.

See: https://github.com/SCOREC/EnGPar/blob/master/partition/Multilevel/engpar_parmetis.cpp#L148-L152
