### ISSUE TITLE
setup nightly cdash testing

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/EnGPar#2]
The phastaChef repo has the necessary cdash and cmake files to set this up:
https://github.com/PHASTA/phastaChef/tree/master/cdash
https://github.com/PHASTA/phastaChef/tree/master/test

**Comment by diamog** [comment]
A test has been submitted to cdash manually:
http://my.cdash.org/index.php?project=EnGPar&date=

**Comment by diamog** [comment]
cron setup. Will close after successfully run at night

**Comment by cwsmith** [comment]
It's not clear what the error is, but the nightly build is failing:
http://my.cdash.org/index.php?project=EnGPar

**Comment by diamog** [comment]
yeah I've gone back to try and fix it a couple of times. I'll try messing with it again

**Comment by diamog** [comment]
Any idea why the error isn't being listed? I guess it must be some problem in the start of the job submission

**Comment by diamog** [comment]
ok it should work as of this commit: https://github.com/SCOREC/EnGPar/commit/c25f6b4978cc3e3b71da064f663f66ba3afdea2a
We shall see tomorrow if it works when I dont submit it myself.

**Comment by cwsmith** [comment]
The tests are failing:
http://my.cdash.org/viewTest.php?onlyfailed&buildid=1243288

My guess is an MPI mismatch; the build is using `/usr/local/openmpi`
http://my.cdash.org/viewBuildError.php?type=1&buildid=1243288
but the tests use `/usr/bin/mpirun`:
http://my.cdash.org/testDetails.php?test=32673298&build=1243288
(click 'show command line')

**Comment by diamog** [comment]
Okay its fixed here: https://github.com/SCOREC/EnGPar/commit/741dd139a737c6d5bc6e126af58a4c27a5a7f85f

I got to run a "nightly test" at 11:33 which worked so assuming 2am isn't a disease we should have nightly tests up and running.
