### ISSUE TITLE
pointer packing broken on big endian systems

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/EnGPar#21]
On big endian systems, the integer to void* to char  to integer conversion here

https://github.com/SCOREC/EnGPar/blob/4147115cc4bbf6489e529594522e16f05b1d1abb/agi/agi_typeconvert.cpp#L4-L10

assumes the int is stored in the lower four bytes of the pointer - on big endian it is stored in the upper four bytes.

We should replace the void* conversion with a simple `lid_t*` (typedef'd as int*) and figure out how to make the iterators on opaque pointers work.  
https://github.com/SCOREC/EnGPar/tree/027d7ecc4edb0298676348bf788820a57333d895/agi/Iterators

**Comment by cwsmith** [comment]
If the types are set during compilation this problem will go away.

**Comment by cwsmith** [comment]
Is this fixed with https://github.com/SCOREC/EnGPar/commit/e9598e91fc83a164b92a60a43de14943419b2457 ?

**Comment by diamog** [comment]
Runs with the new compile-time definitions run on AMOS with big endian enabled with both 32-bit and 64-bit local indices.
