### ISSUE TITLE
Vertex balancer doesn't balance

### ISSUE THREAD

**Issue by diamog** [SCOREC/EnGPar#22]
Eric reports vertex balancer not balancing even when tol<imb

**Comment by cwsmith** [comment]
It looks like the only supported way to specify balance tolerance is through the `addPriority` call:

https://github.com/SCOREC/EnGPar/blob/2588f9873cd2e608cef0cf3cf99ceaa1827b97a6/partition/Diffusive/engpar_diffusive_input.cpp#L18

The older interface is hard coded for 10% imbalance:

https://github.com/SCOREC/EnGPar/blob/bdd53c2fef61176623337dc916f049ffe39b2e36/partition/Diffusive/src/engpar_vtxBalancer.cpp#L14

https://github.com/SCOREC/EnGPar/blob/4f8c6f912e57f26ffc11ecb0a7be6c63501f2163/partition/Diffusive/src/engpar_balancer.cpp#L184

**Comment by diamog** [comment]
I'm thinking of solving it by using the input to balance as a max tolerance for all entity types. That way the vertex balancer can be modified but has a default of 1.1 and also doesn't require an API change.

**Comment by cwsmith** [comment]
How many other 'balance' apis are broken by this?  If there are only a few, I'd vote for a single interface to specifying the actions of the diffusive balancer.

**Comment by diamog** [comment]
We could remove the Vertex Balancer. It serves no purpose beyond initial testing.

**Comment by diamog** [comment]
The input fix has been done so Eric can try out balancing with the vertex balancer. API changes and removing the old balancer can be done at a later time.
