### ISSUE TITLE
use target_* to pass compile flags to downstream packages

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/EnGPar#24]
In CMakeLists.txt we call `add_definition` to set the index type, the endianness, parmetis use, and kokkos use.  For the settings that affect downstream packages we should use `target_compile_definitions` as done [here](https://github.com/SCOREC/core/commit/efe6e59dfccb37d65b1adb72c5f7507633547818) to pass these along - otherwise there could be strange errors.

**Comment by diamog** [comment]
I did an initial use of it. It works within engpar for future libraries, but when using the installation the definitions are still missing. Are there cmake functions to run when finding the libraries to receive the definitions?

**Comment by cwsmith** [comment]
I think we'll need to export the package and its deps

https://cmake.org/cmake/help/v3.10/command/install.html#installing-exports

https://cmake.org/cmake/help/v3.10/manual/cmake-packages.7.html#creating-packages

https://github.com/SCOREC/core/blob/2472c570dc3a9e5acc23146288822733759558a1/cmake/bob.cmake#L142-L143

to have them written into an `engparConfig.cmake` that `find_package(engpar)` would read.  IIUC, we then do something like `target_link_libraries(targetname engpar)` and cmake will add in the compile and link dependencies.

**Comment by diamog** [comment]
Commit cd7e8a983801b3ff441a4418920db1e7f6938b32 added the neccessary changes to create the configure scripts.
