### ISSUE TITLE
Multiple graph construction from mesh

### ISSUE THREAD

**Issue by LucasBondDavis** [SCOREC/EnGPar#27]
When I delete multiple graphs constructed from the same mesh I get a segfault. It may be a result of this tag being reused https://github.com/SCOREC/EnGPar/blob/master/interfaces/apfGraph.cpp#L130-L131.

**Comment by diamog** [comment]
The commit above adds an argument to the createAPFGraph functions that uses a name to differentiate the numberings used. This should fix the crash you are seeing if you use different names for each graph created.
