### ISSUE TITLE
kk_hg_bfs: where to place kokkos support functions and typedefs

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/EnGPar#32]
The typedefs and functions here:

https://github.com/SCOREC/EnGPar/blob/ea0caa1b5309674a8598e68c405ffa676b53d212/agi/agiConstruct.cpp#L744-L767

need to be placed in a common location so we don't have to repeat them for bfs and other future kokkos  code.

https://github.com/SCOREC/EnGPar/blob/e4300a34fb2340e76360d0710238f7679200af67/partition/Coloring/engpar_kokkosColoring.h#L23-L25

https://github.com/SCOREC/EnGPar/blob/e4300a34fb2340e76360d0710238f7679200af67/partition/Coloring/engpar_kokkosColoring.cpp#L8-L23

**Comment by diamog** [comment]
If the support functions don't depend on the graph, then I would suggest putting them in the support directory.
