### ISSUE TITLE
Add doxygen to webspace

### ISSUE THREAD

**Issue by diamog** [SCOREC/EnGPar#6]

**Comment by diamog** [comment]
@cwsmith Did we ever get the space to put this on?

**Comment by cwsmith** [comment]
I pinged Bob about this.

**Comment by diamog** [comment]
thank you

**Comment by cwsmith** [comment]
you can now write to /net/web/engpar

bob is working on having the contents appear on www.scorec.rpi.edu

**Comment by cwsmith** [comment]
done as of 8113b2ea93023bc489fe9909d0f92c6a2f2809eb
