### ISSUE TITLE
intel 15 compiler and c++11

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/EnGPar#8]
When using the intel 15 compiler compilation fails; the `make VERBOSE=1` log is here:
https://ptpb.pw/tp2b

EnGPar SHA-1: 486d9c7

Intel compiler:
```
$ icc --version
icc (ICC) 15.0.3 20150407
```

The GNU compiler (4.8.5) works without issue on this system (Pleiades).

Based on the error, I think this is an issue with how the intel C++ compiler handles C++11 versus GNU.

**Comment by diamog** [comment]
Try the recent commit. I got it to compile with an intel compiler, however its having some issues while running that I am still working through. Knowing that it compiles on your end would be great though.

**Comment by diamog** [comment]
As of this commit: https://github.com/SCOREC/EnGPar/commit/fa0ef79537de843741b43dabe4e6ec8d5ed0ce96 the tests pass with the changes for the intel compiler. Let me know if there are still issues

**Comment by cwsmith** [comment]
Thanks.  What was the problem?

**Comment by cwsmith** [comment]
`public.h` appears to be missing

**Comment by diamog** [comment]
The problem seemed to stem from intel compilers not supporting statically sized arrays (those defined on the stack) as template entries for the STL containers. While GNU seemed to have no problem with it. It avoided a lot of small memory allocations/deallocations but now its all memory declared on the heap and (hopefully) deallocated
